# Generated by Django 3.2.5 on 2021-07-25 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fieldwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='field_user',
        ),
        migrations.AddField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='observations', related_query_name='observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FieldUser',
        ),
    ]
